run_as shiny;
access_log /dev/stdout combined;

disable_protocols xhr_streaming xhr_polling jsonp_polling iframe_xhr_polling iframe_htmlfile;

server {
  listen 3838;
  app_init_timeout 300;
  app_idle_timeout 300;
  location / {
    app_dir /app;
    log_dir /var/log/shiny-server;
    sanitize_errors off;
  }
}